using Etp.Reporting.Infrastructure.SqlServer;
using Etp.Reporting.Reporting;

namespace Etp.Reporting.SqlServer.IntegrationTests;

public sealed class PhaseFiveStoreCatalogTests
{
    [Fact]
    public async Task Newly_configured_store_appears_in_dsr_and_combined_manual_totals_and_retired_masters_are_absent()
    {
        await using var db=new StoreDatabase();await db.InitializeAsync();
        var repository=new Phase2OperationsRepository(db.Fixture.ConnectionString);
        await repository.UpsertMasterValueAsync("STORE","EAST","East branch","APPROVED",true,"New shop");
        await db.Fixture.ExecuteAsync("UPDATE dbo.stores SET is_active=CASE WHEN store_code='EAST' THEN 1 ELSE 0 END;");
        var catalog=new StoreCatalogRepository(db.Fixture.ConnectionString);
        Assert.Equal(["EAST"],await catalog.ActiveCodesAsync());
        var day=new DateOnly(2026,8,25);
        await new DataTruthMasterRepository(db.Fixture.ConnectionString).SaveMonthlyTargetAsync(new("EAST",new(2026,8,1),3100m));
        var document=await new OperationalReportRepository(db.Fixture.ConnectionString).LoadDailySalesReportDocumentAsync(day);
        var store=Assert.Single(document.Stores);
        Assert.Equal("EAST",store.StoreCode);Assert.Equal("East branch",store.DisplayName);
        Assert.Equal(["EAST","COMBINED"],document.EveningSheets.Select(x=>x.StoreCode));
        Assert.Equal(3100m,document.EveningSheets.Single(x=>x.StoreCode=="COMBINED").StoreTarget);
        Assert.Equal(100m,document.EveningSheets.Single(x=>x.StoreCode=="EAST").DayTarget);
        var pack = await new DailyReportingPackService(db.Fixture.ConnectionString).GenerateCombinedAsync(day, "Synthetic catalogue test");
        Assert.Contains("East branch", pack.Title);
        Assert.DoesNotContain("Titan", pack.Title, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Helios", pack.Title, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(pack.Tables, table => table.Name.Contains("East branch", StringComparison.Ordinal) && table.Name.Contains("DSR", StringComparison.Ordinal));
        Assert.All(pack.Tables, table =>
        {
            Assert.DoesNotContain("Titan", table.Name, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("Helios", table.Name, StringComparison.OrdinalIgnoreCase);
        });
        Assert.Equal(DBNull.Value,await db.Fixture.ExecuteAsync("SELECT OBJECT_ID(N'dbo.controlled_master_values',N'U')"));
        await Assert.ThrowsAsync<ArgumentException>(()=>repository.UpsertMasterValueAsync("TENDER","UNUSED","Unused","APPROVED",true,"Not used"));
    }

    [Theory]
    [InlineData(1)]
    [InlineData(3)]
    public async Task Latest_combined_day_requires_every_active_store_and_ignores_newer_partial_or_inactive_sources(int activeCount)
    {
        await using var db=new StoreDatabase(); await db.InitializeAsync();
        var repository=new Phase2OperationsRepository(db.Fixture.ConnectionString);
        await db.Fixture.ExecuteAsync("UPDATE dbo.stores SET is_active=0;");
        for(var index=1;index<=activeCount;index++)
            await repository.UpsertMasterValueAsync("STORE",$"BRANCH{index}",$"Branch {index}","APPROVED",true,"Synthetic active-store test");
        await repository.UpsertMasterValueAsync("STORE","RETIRED","Retired branch","APPROVED",false,"Synthetic inactive-store test");
        var first=new DateOnly(2026,8,25); var partial=first.AddDays(1); var latest=first.AddDays(2);
        foreach(var code in Enumerable.Range(1,activeCount).Select(index=>$"BRANCH{index}")) await AddFile(code,first);
        for(var index=1;index<activeCount;index++) await AddFile($"BRANCH{index}",partial);
        await AddFile("RETIRED",partial);
        Assert.Equal(first,await repository.LoadLatestCombinedBusinessDateAsync(CancellationToken.None));
        foreach(var code in Enumerable.Range(1,activeCount).Select(index=>$"BRANCH{index}")) await AddFile(code,latest);
        Assert.Equal(latest,await repository.LoadLatestCombinedBusinessDateAsync(CancellationToken.None));
        await db.Fixture.ExecuteAsync("UPDATE dbo.stores SET is_active=0;");
        Assert.Null(await repository.LoadLatestCombinedBusinessDateAsync(CancellationToken.None));

        async Task AddFile(string code,DateOnly date)
        {
            // Store/date values here are generated by this synthetic fixture, never external input.
            await db.Fixture.ExecuteAsync($"""
                DECLARE @batch uniqueidentifier=NEWID();
                INSERT dbo.import_batches(import_batch_id,status,period_start,period_end,started_utc)
                VALUES(@batch,'Completed','{date:yyyyMMdd}','{date:yyyyMMdd}',SYSUTCDATETIME());
                INSERT dbo.import_files(import_batch_id,original_file_name,source_sha256,size_bytes,report_code,store_code,business_date,period_start,period_end)
                VALUES(@batch,'synthetic-{code}-{date:yyyyMMdd}.xlsx',LOWER(CONVERT(varchar(64),HASHBYTES('SHA2_256','{code}-{date:yyyyMMdd}'),2)),1,'R025','{code}','{date:yyyyMMdd}','{date:yyyyMMdd}','{date:yyyyMMdd}');
                """);
        }
    }

    private sealed class StoreDatabase:IAsyncDisposable
    {
        public SqlDatabaseFixture Fixture {get;}=new();
        public Task InitializeAsync()=>Fixture.InitializeAsync();
        public async ValueTask DisposeAsync()=>await Fixture.DisposeAsync();
    }
}
