using System.Text;
using System.Text.RegularExpressions;
using Etp.Reporting.Domain.Imports;
using Etp.Reporting.Import.Profiles;
using Etp.Reporting.Import.Service;

namespace Etp.Reporting.SqlServer.Tests;

/// <summary>
/// Service interim (S-2), decision 15, 3 Oct 2026; lane L2. Section B_SERVICE_LANDING of migration 0048 holds one
/// landing table, file index, locked-day trigger, append procedure and DENY/GRANT per importable Service family,
/// generated by scripts/service-centre/generate_landing_sql.py from the catalogue. These tests read the shipped text;
/// the SQL behaviour is covered by ServiceLandingSqlTests in the SQL integration suite.
/// </summary>
public sealed partial class ServiceLandingMigrationTests
{
    private const string MigrationName = "0048_service_centre_interim.sql";
    private const string BeginMarker = "-- >>> B_SERVICE_LANDING begin";
    private const string EndMarker = "-- <<< B_SERVICE_LANDING end";

    private static readonly string[] NoTable = ["S001", "S005", "S027", "S028", "S038"];

    public static TheoryData<string> ImportableCodes()
    {
        var data = new TheoryData<string>();
        foreach (var code in ServiceInterimFamilies.Importable.Order(StringComparer.Ordinal)) data.Add(code);
        return data;
    }

    [Fact]
    public void Section_is_byte_identical_to_what_the_generator_gives_for_the_catalogue()
    {
        // Golden test: a catalogue change that is not regenerated into 0048 (or a hand edit of the section) fails here.
        // The renderer below is the C# twin of generate_landing_sql.py; keep the two identical.
        var expected = RenderSection(LandingFamilies());
        var actual = Section();
        if (expected != actual)
        {
            var at = Enumerable.Range(0, Math.Min(expected.Length, actual.Length)).FirstOrDefault(i => expected[i] != actual[i]);
            var line = actual[..Math.Min(at, actual.Length)].Count(character => character == '\n') + 1;
            Assert.Fail($"Section B_SERVICE_LANDING differs from the catalogue at section line {line}. "
                + "Run: python scripts/service-centre/generate_landing_sql.py");
        }
    }

    [Fact]
    public void Section_has_exactly_one_table_per_importable_family_and_none_for_the_others()
    {
        var importable = ServiceInterimFamilies.Importable.ToHashSet(StringComparer.Ordinal);
        Assert.Equal(36, importable.Count);
        var tables = TableRegex().Matches(Section()).Select(match => match.Groups[1].Value.ToUpperInvariant()).ToArray();
        Assert.Equal(36, tables.Length);
        Assert.Equal(tables.Length, tables.Distinct().Count());
        Assert.Equal(importable.Order(StringComparer.Ordinal), tables.Order(StringComparer.Ordinal));
        foreach (var code in NoTable)
        {
            Assert.DoesNotContain(code, importable);
            Assert.DoesNotContain($"etp_landing_{code.ToLowerInvariant()}", Section(), StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public void Catalogue_has_a_landing_entry_for_every_importable_family()
    {
        var families = LandingFamilies();
        Assert.Equal(ServiceInterimFamilies.Importable.Order(StringComparer.Ordinal), families.Select(family => family.ReportCode));
        Assert.All(families, family =>
        {
            Assert.Equal(BusinessUnit.Service, family.BusinessUnit);
            Assert.False(family.IsTyped);
            Assert.Equal($"etp_landing_{family.ReportCode.ToLowerInvariant()}", family.TableName);
        });
    }

    [Theory]
    [MemberData(nameof(ImportableCodes))]
    public void Table_columns_and_types_follow_the_catalogue_in_order(string code)
    {
        var family = Family(code);
        var block = FamilyBlock(code);
        var table = family.TableName;
        Assert.Contains($"IF OBJECT_ID(N'dbo.{table}', N'U') IS NULL\nCREATE TABLE dbo.[{table}] (\n", block, StringComparison.Ordinal);
        var create = Regex.Match(block, $@"CREATE TABLE dbo\.\[{table}\] \(\n(?<body>.*?)\n\);", RegexOptions.Singleline);
        Assert.True(create.Success, $"{code}: no CREATE TABLE");
        var lines = create.Groups["body"].Value.Split('\n');
        Assert.Equal(" etp_row_id bigint IDENTITY PRIMARY KEY,", lines[0]);
        Assert.Equal(" import_file_id bigint NOT NULL REFERENCES dbo.import_files(import_file_id),", lines[1]);
        Assert.Equal(" source_lineage_id bigint NOT NULL UNIQUE REFERENCES dbo.source_lineage(source_lineage_id),", lines[2]);
        Assert.Equal(" content_key varchar(80) NOT NULL,", lines[3]);
        var columns = lines.Skip(4).Select(line => ColumnRegex().Match(line)).ToArray();
        Assert.All(columns, match => Assert.True(match.Success, match.Value));
        Assert.Equal(family.Columns.Select(column => column.CanonicalField), columns.Select(match => match.Groups[1].Value));
        Assert.Equal(family.Columns.Select(column => SqlType(column.DataType)), columns.Select(match => match.Groups[2].Value));
    }

    [Theory]
    [MemberData(nameof(ImportableCodes))]
    public void Index_and_locked_day_trigger_match_the_0018_template(string code)
    {
        var table = Family(code).TableName;
        var block = FamilyBlock(code);
        Assert.Contains($"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{table}_file' AND object_id = OBJECT_ID(N'dbo.{table}'))\n"
            + $" CREATE INDEX IX_{table}_file ON dbo.[{table}](import_file_id);\n", block, StringComparison.Ordinal);
        var trigger = Trigger0018().Replace("EXEC(N'CREATE TRIGGER ", "EXEC(N'CREATE OR ALTER TRIGGER ", StringComparison.Ordinal)
            .Replace("etp_landing_sor_ageing", table, StringComparison.Ordinal);
        Assert.Contains("\n" + trigger + "\n", block, StringComparison.Ordinal);
        Assert.Single(Regex.Matches(block, "CREATE OR ALTER TRIGGER "));
    }

    [Theory]
    [MemberData(nameof(ImportableCodes))]
    public void Append_procedure_takes_the_catalogue_columns_in_order_with_the_0025_guards(string code)
    {
        var family = Family(code);
        var table = family.TableName;
        var block = FamilyBlock(code);
        var procedure = Regex.Match(block, $@"EXEC\(N'CREATE OR ALTER PROCEDURE dbo\.append_{table}\n @file bigint,@lineage bigint,@key varchar\(80\),\n(?<parameters>.*?)\nAS BEGIN\n",
            RegexOptions.Singleline);
        Assert.True(procedure.Success, $"{code}: no append procedure");
        var parameters = procedure.Groups["parameters"].Value.Split('\n').Select(line => ParameterRegex().Match(line)).ToArray();
        Assert.All(parameters, match => Assert.True(match.Success, match.Value));
        // PhaseOneImportPersistence passes @v0..@vN positionally in catalogue Columns order.
        Assert.Equal(Enumerable.Range(0, family.Columns.Count).Select(index => index.ToString()), parameters.Select(match => match.Groups[1].Value));
        Assert.Equal(family.Columns.Select(column => SqlType(column.DataType)), parameters.Select(match => match.Groups[2].Value));

        Assert.Contains(Guards0025().Replace("''SOR_AGEING''", $"''{code}''", StringComparison.Ordinal), block, StringComparison.Ordinal);
        Assert.Contains($"f.report_code=''{code}'')", block, StringComparison.Ordinal);
        Assert.Contains($" INSERT dbo.[{table}](import_file_id,source_lineage_id,content_key,{string.Join(',', family.Columns.Select(column => $"[{column.CanonicalField}]"))})\n"
            + $" VALUES(@file,@lineage,@key,{string.Join(',', family.Columns.Select((_, index) => $"@v{index}"))});\n"
            + " INSERT dbo.etp_import_content(import_file_id,source_row_number,content_key)\n"
            + " SELECT @file,source_row_number,@key FROM dbo.source_lineage WHERE source_lineage_id=@lineage;\nEND');\n", block, StringComparison.Ordinal);
    }

    [Theory]
    [MemberData(nameof(ImportableCodes))]
    public void Writes_are_denied_and_the_append_procedure_is_granted(string code)
    {
        var table = Family(code).TableName;
        var block = FamilyBlock(code);
        Assert.Contains($"DENY INSERT,UPDATE,DELETE ON dbo.[{table}] TO etp_store_manager,etp_viewer;\n", block, StringComparison.Ordinal);
        Assert.Contains($"GRANT EXECUTE ON dbo.append_{table} TO etp_store_manager,etp_owner;\n", block, StringComparison.Ordinal);
    }

    [Fact]
    public void Section_is_idempotent_and_holds_nothing_but_landing_objects()
    {
        var section = Section();
        Assert.Equal(36, Regex.Matches(section, @"^IF OBJECT_ID\(N'dbo\.etp_landing_s\d{3}', N'U'\) IS NULL\nCREATE TABLE ", RegexOptions.Multiline).Count);
        Assert.Equal(36, Regex.Matches(section, @"^CREATE TABLE ", RegexOptions.Multiline).Count);
        Assert.Equal(36, Regex.Matches(section, @"^IF NOT EXISTS \(SELECT 1 FROM sys\.indexes ", RegexOptions.Multiline).Count);
        Assert.Equal(36, Regex.Matches(section, @"CREATE INDEX ").Count);
        Assert.Equal(36, Regex.Matches(section, @"^EXEC\(N'CREATE OR ALTER TRIGGER ", RegexOptions.Multiline).Count);
        Assert.Equal(36, Regex.Matches(section, @"^EXEC\(N'CREATE OR ALTER PROCEDURE ", RegexOptions.Multiline).Count);
        Assert.DoesNotMatch(@"(?i)\b(BEGIN\s+TRAN|COMMIT|ROLLBACK)\b", section);
        Assert.DoesNotMatch(@"(?i)\bCREATE\s+(VIEW|FUNCTION|SCHEMA|ROLE|USER)\b", section);
        Assert.DoesNotMatch(@"(?i)\bdbo\.(stores|business_units|import_profiles)\b", section);
        Assert.DoesNotMatch(@"(?i)\b(UPDATE|DELETE)\s+(dbo\.)?\[?(import_files|source_lineage|etp_landing_)", section);
        Assert.DoesNotMatch(@"(?i)\bpromote_import_superset\s+@", section);
    }

    [Fact]
    public void Landing_objects_live_only_inside_the_section_markers()
    {
        var script = Script();
        Assert.Single(Regex.Matches(script, Regex.Escape(BeginMarker) + "$", RegexOptions.Multiline));
        Assert.Single(Regex.Matches(script, Regex.Escape(EndMarker) + "$", RegexOptions.Multiline));
        var begin = script.IndexOf(BeginMarker + "\n", StringComparison.Ordinal);
        var end = script.IndexOf("\n" + EndMarker, StringComparison.Ordinal);
        Assert.True(begin >= 0 && end > begin);
        Assert.True(script.IndexOf("-- >>> A_SERVICE_STORE begin", StringComparison.Ordinal) < begin);
        Assert.True(script.IndexOf("-- >>> C_SERVICE_READ begin", StringComparison.Ordinal) > end);
        var outside = script[..begin] + script[(end + EndMarker.Length + 1)..];
        Assert.DoesNotMatch(@"(?i)CREATE\s+(TABLE|INDEX|OR\s+ALTER\s+TRIGGER|TRIGGER|OR\s+ALTER\s+PROCEDURE|PROCEDURE)\s+[^\n]*etp_landing_s\d{3}", outside);
        Assert.DoesNotMatch(@"(?i)append_etp_landing_s\d{3}", outside);
        Assert.DoesNotMatch(@"(?i)DENY\s+[^\n]*etp_landing_s\d{3}", outside);
    }

    // ----- the C# twin of generate_landing_sql.py -----

    private static readonly string TriggerTemplate =
        "EXEC(N'CREATE OR ALTER TRIGGER dbo.trg_{table}_locked ON dbo.[{table}] AFTER INSERT,UPDATE,DELETE AS BEGIN SET NOCOUNT ON; "
        + "IF EXISTS(SELECT 1 FROM (SELECT import_file_id FROM inserted UNION SELECT import_file_id FROM deleted) x "
        + "JOIN dbo.import_files f ON f.import_file_id=x.import_file_id JOIN dbo.daily_reporting_days d ON d.store_code=f.store_code "
        + "AND d.business_date BETWEEN f.period_start AND f.period_end WHERE d.status=''LOCKED'') "
        + "THROW 51243,''A day inside this export is finalised. Reopen it before changing its data.'',1; END');";

    private const string GuardsTemplate = """
        AS BEGIN
         SET NOCOUNT ON; SET XACT_ABORT ON;
         IF COALESCE(IS_ROLEMEMBER(''etp_store_manager''),0)<>1 AND COALESCE(IS_ROLEMEMBER(''etp_owner''),0)<>1
            AND COALESCE(IS_SRVROLEMEMBER(''sysadmin''),0)<>1
          THROW 51420,''Owner or Store Manager permission is required.'',1;
         IF @@TRANCOUNT=0 THROW 51422,''Import writes require an enclosing transaction.'',1;
         IF NOT EXISTS(SELECT 1 FROM dbo.import_files f WITH(UPDLOCK,HOLDLOCK)
           JOIN dbo.import_batches b ON b.import_batch_id=f.import_batch_id
           WHERE f.import_file_id=@file AND f.is_superseded=0 AND f.data_truth_version=1 AND b.status=''Processing'')
          THROW 51422,''The source import is not open for writing.'',1;
         IF NOT EXISTS(SELECT 1 FROM dbo.source_lineage l JOIN dbo.import_files f ON f.import_file_id=l.import_file_id
           WHERE l.source_lineage_id=@lineage AND l.import_file_id=@file AND f.report_code=''{code}'')
          THROW 51422,''The source row does not belong to this report import.'',1;
        """;

    private static readonly string[] HeaderLines =
    [
        "-- Generated by scripts/service-centre/generate_landing_sql.py from src/Etp.Reporting.Import/Profiles/EtpReportFamilies.json.",
        "-- Regenerate rather than edit; ServiceLandingMigrationTests fails when this section and the catalogue disagree.",
        "-- The {count} importable Service families (ServiceInterimFamilies.Importable), each in the 1.9.3 landing shape:",
        "-- table (0018), file index, locked-day trigger (0018 text), append procedure (0025 guards), DENY and GRANT.",
        "-- No table for S001 (derived), S005 and S038 (not needed) or S027 and S028 (deferred to P8).",
        "-- dbo.promote_import_superset needs no Service block: its content-key superset check over dbo.etp_import_content",
        "-- covers untyped families, and the per-report blocks are only for typed Retail tables. 0025 is not edited.",
        "-- No stores row (section A owns AW330), no import_profiles seed and no transaction (the runner supplies it).",
    ];

    private static string RenderSection(IReadOnlyList<EtpReportFamily> families)
    {
        var text = new StringBuilder();
        foreach (var line in HeaderLines) text.Append(line.Replace("{count}", families.Count.ToString(), StringComparison.Ordinal)).Append('\n');
        foreach (var family in families) text.Append('\n').Append(RenderFamily(family));
        return text.ToString();
    }

    private static string RenderFamily(EtpReportFamily family)
    {
        var code = family.ReportCode;
        var table = family.TableName;
        var columns = family.Columns;
        var last = columns.Count - 1;
        var lines = new List<string>
        {
            $"-- {code} {family.Name} ({columns.Count} columns)",
            $"IF OBJECT_ID(N'dbo.{table}', N'U') IS NULL",
            $"CREATE TABLE dbo.[{table}] (",
            " etp_row_id bigint IDENTITY PRIMARY KEY,",
            " import_file_id bigint NOT NULL REFERENCES dbo.import_files(import_file_id),",
            " source_lineage_id bigint NOT NULL UNIQUE REFERENCES dbo.source_lineage(source_lineage_id),",
            " content_key varchar(80) NOT NULL,",
        };
        lines.AddRange(columns.Select((column, index) => $" [{column.CanonicalField}] {SqlType(column.DataType)} NULL" + (index < last ? "," : "")));
        lines.AddRange(
        [
            ");",
            "",
            $"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{table}_file' AND object_id = OBJECT_ID(N'dbo.{table}'))",
            $" CREATE INDEX IX_{table}_file ON dbo.[{table}](import_file_id);",
            "",
            TriggerTemplate.Replace("{table}", table, StringComparison.Ordinal),
            "",
            $"EXEC(N'CREATE OR ALTER PROCEDURE dbo.append_{table}",
            " @file bigint,@lineage bigint,@key varchar(80),",
        ]);
        lines.AddRange(columns.Select((column, index) => $" @v{index} {SqlType(column.DataType)}" + (index < last ? "," : "")));
        lines.Add(GuardsTemplate.Replace("\r\n", "\n").Replace("{code}", code, StringComparison.Ordinal));
        lines.Add($" INSERT dbo.[{table}](import_file_id,source_lineage_id,content_key,{string.Join(',', columns.Select(column => $"[{column.CanonicalField}]"))})");
        lines.Add($" VALUES(@file,@lineage,@key,{string.Join(',', columns.Select((_, index) => $"@v{index}"))});");
        lines.AddRange(
        [
            " INSERT dbo.etp_import_content(import_file_id,source_row_number,content_key)",
            " SELECT @file,source_row_number,@key FROM dbo.source_lineage WHERE source_lineage_id=@lineage;",
            "END');",
            "",
            $"DENY INSERT,UPDATE,DELETE ON dbo.[{table}] TO etp_store_manager,etp_viewer;",
            $"GRANT EXECUTE ON dbo.append_{table} TO etp_store_manager,etp_owner;",
        ]);
        return string.Join('\n', lines) + "\n";
    }

    private static string SqlType(CanonicalDataType type) => type switch
    {
        CanonicalDataType.Text or CanonicalDataType.Identifier => "nvarchar(max)",
        CanonicalDataType.Decimal => "decimal(19,4)",
        CanonicalDataType.Date => "date",
        CanonicalDataType.Integer => "int",
        _ => throw new InvalidOperationException($"No landing column type for {type}."),
    };

    // ----- helpers -----

    private static IReadOnlyList<EtpReportFamily> LandingFamilies()
    {
        var importable = ServiceInterimFamilies.Importable.ToHashSet(StringComparer.Ordinal);
        return EtpReportFamilyRegistry.Families
            .Where(family => importable.Contains(family.ReportCode) && !family.Derived)
            .OrderBy(family => family.ReportCode, StringComparer.Ordinal).ToArray();
    }

    private static EtpReportFamily Family(string code) => Assert.Single(LandingFamilies(), family => family.ReportCode == code);

    private static string RepositoryRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Etp.Reporting.slnx"))) dir = dir.Parent;
        Assert.NotNull(dir);
        return dir.FullName;
    }

    private static string ReadMigration(string name) =>
        File.ReadAllText(Path.Combine(RepositoryRoot(), "database", "migrations", name)).Replace("\r\n", "\n");

    private static string Script() => ReadMigration(MigrationName);

    private static string Section()
    {
        var script = Script();
        var begin = script.IndexOf(BeginMarker + "\n", StringComparison.Ordinal);
        var end = script.IndexOf("\n" + EndMarker, StringComparison.Ordinal);
        Assert.True(begin >= 0 && end >= begin, "0048 has no B_SERVICE_LANDING section.");
        return script[(begin + BeginMarker.Length + 1)..(end + 1)];
    }

    private static string FamilyBlock(string code)
    {
        var section = Section();
        var start = section.IndexOf($"\n-- {code} ", StringComparison.Ordinal);
        Assert.True(start >= 0, $"{code}: no block in section B");
        var next = Regex.Match(section[(start + 1)..], @"\n-- S\d{3} ");
        return next.Success ? section[(start + 1)..(start + 1 + next.Index + 1)] : section[(start + 1)..];
    }

    // The 0018 locked-day trigger as shipped for the last landing family (SOR_AGEING).
    private static string Trigger0018()
    {
        var line = ReadMigration("0018_etp_family_tables.sql").Split('\n')
            .Single(text => text.StartsWith("EXEC(N'CREATE TRIGGER dbo.trg_etp_landing_sor_ageing_locked ", StringComparison.Ordinal));
        return line.TrimEnd();
    }

    // The 0025 append-procedure guards as shipped for SOR_AGEING, from AS BEGIN to the report_code THROW.
    private static string Guards0025()
    {
        var script = ReadMigration("0025_phase_integration_write_boundary.sql");
        var procedure = script.IndexOf("EXEC(N'CREATE OR ALTER PROCEDURE dbo.append_etp_landing_sor_ageing\n", StringComparison.Ordinal);
        Assert.True(procedure >= 0);
        var begin = script.IndexOf("\nAS BEGIN\n", procedure, StringComparison.Ordinal) + 1;
        const string last = "THROW 51422,''The source row does not belong to this report import.'',1;";
        var end = script.IndexOf(last, begin, StringComparison.Ordinal) + last.Length;
        return script[begin..end];
    }

    [GeneratedRegex(@"^CREATE TABLE dbo\.\[etp_landing_(s\d{3})\] \(", RegexOptions.Multiline)]
    private static partial Regex TableRegex();

    [GeneratedRegex(@"^ \[([a-z0-9_]+)\] (nvarchar\(max\)|decimal\(19,4\)|date|int) NULL,?$")]
    private static partial Regex ColumnRegex();

    [GeneratedRegex(@"^ @v(\d+) (nvarchar\(max\)|decimal\(19,4\)|date|int),?$")]
    private static partial Regex ParameterRegex();
}
