SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF EXISTS(SELECT 1 FROM sys.database_principals WHERE name=N'NT AUTHORITY\SYSTEM')
BEGIN
    DENY DELETE ON SCHEMA::dbo TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.application_users TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.application_user_history TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.controlled_master_values TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.controlled_master_history TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.watch_folder_settings TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.stores TO [NT AUTHORITY\SYSTEM];
    DENY INSERT,UPDATE,DELETE ON dbo.schema_migrations TO [NT AUTHORITY\SYSTEM];
    DENY UPDATE,DELETE ON dbo.operational_audit TO [NT AUTHORITY\SYSTEM];
    DENY UPDATE,DELETE ON dbo.automation_runs TO [NT AUTHORITY\SYSTEM];
END;

COMMIT TRANSACTION;
