-- Service Centre interim import (Service review step S-2), decision 15, 3 Oct 2026.
-- Lands the consolidated and raw Service Centre exports in their own landing tables on the
-- 1.9.3 planner-1 family route, and adds read-only views over them for four Service screens.
-- Design: Reference/Work in progress 2026-10-03/service/SERVICE-INTERIM-DESIGN.md (section 5).
--
-- Numbering: this file must ship after 0046/0047 of 1.9.4. Until release/1.9.4 is merged into
-- feature/service-interim, the migration contiguity test fails on this branch; that is expected.
-- 1.10.0 numbers from 0049.
--
-- The migration runner applies this entire script in one transaction, so it has no BEGIN or COMMIT.
-- Every statement is idempotent (OBJECT_ID/COL_LENGTH guards, insert-if-missing, CREATE OR ALTER),
-- and every CREATE VIEW, PROCEDURE or TRIGGER runs through EXEC(N'...').
-- It never updates or deletes import_files, source_lineage, landing or fact tables.
-- New SQL error numbers come only from docs/service-centre/SERVICE-INTERIM-NUMBERS.md (51900-51929).
-- Each section has one owner and changes only what lies between its own begin and end markers.
SET XACT_ABORT ON;

-- >>> A_SERVICE_STORE begin
-- Owner: lane L0. The Service Centre is store AW330 of a new SERVICE business unit, and it is INACTIVE.
-- An active AW330 would break Retail: Phase2OperationsRepository.LoadLatestCombinedBusinessDateAsync needs
-- an R025 import for every active store, DailyReportingPackService.GenerateCombinedAsync builds one pack per
-- active store, and the DSR and evening store lists would include it (design section 6).
-- The Retail stores keep their NULL business_unit_id, which means Retail; they are not touched.
IF NOT EXISTS(SELECT 1 FROM dbo.business_units WHERE business_unit_code='SERVICE')
BEGIN
  INSERT dbo.business_units(business_unit_code,business_unit_name,is_active)
  VALUES('SERVICE',N'Service Centre',1);
END;

-- Never update an existing AW330 row: if one exists, leave it alone and say so.
IF NOT EXISTS(SELECT 1 FROM dbo.stores WHERE store_code='AW330')
BEGIN
  INSERT dbo.stores(store_code,store_name,business_unit_id,is_active,modified_by,modified_utc,change_reason)
  SELECT 'AW330',N'Service Centre AW330',b.business_unit_id,0,SUSER_SNAME(),SYSUTCDATETIME(),
    N'Service Centre store seeded by the Service interim import (0048); not a shop store'
  FROM dbo.business_units b WHERE b.business_unit_code='SERVICE';
END
ELSE
BEGIN
  PRINT N'0048: a store AW330 already exists, so it was left as it is.';
END;

-- A store of the SERVICE unit can never be active, and cannot be moved out of the SERVICE unit
-- (which would make it a Retail shop store). Settings > Stores maps 51900 to a friendly message.
EXEC(N'CREATE OR ALTER TRIGGER dbo.trg_stores_service_unit_inactive ON dbo.stores
AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.business_units b ON b.business_unit_id=i.business_unit_id
   WHERE b.business_unit_code=''SERVICE'' AND i.is_active=1)
  THROW 51900,''A Service Centre store cannot be made an active shop store.'',1;
 IF EXISTS(SELECT 1 FROM deleted d JOIN dbo.business_units b ON b.business_unit_id=d.business_unit_id
   JOIN inserted i ON i.store_id=d.store_id
   WHERE b.business_unit_code=''SERVICE'' AND (i.business_unit_id IS NULL OR i.business_unit_id<>d.business_unit_id))
  THROW 51900,''A Service Centre store cannot be made an active shop store.'',1;
END');
-- <<< A_SERVICE_STORE end

-- >>> B_SERVICE_LANDING begin
-- Owner: lane L2. Generated by scripts/service-centre/generate_landing_sql.py from the catalogue.
-- <<< B_SERVICE_LANDING end

-- >>> C_SERVICE_READ begin
-- Owner: lane L4. Read-rule views over the Service landing tables (design section 4).
-- <<< C_SERVICE_READ end
