namespace Etp.Reporting.TestSupport.Service;

/// <summary>
/// The synthetic Service Centre interim fixtures under <c>tests-dotnet/fixtures/service-interim/</c>, generated by
/// <c>scripts/service-centre/generate_fixtures.py</c> from <c>families.spec.json</c> only (never from a real workbook).
/// A test project links this file and <c>ServiceFixtureExpectations.g.cs</c>, and copies the fixture folder to its output
/// (<c>fixtures/service-interim/**</c>). Rows per family per week are in <see cref="Week1Rows"/> and <see cref="Week2Rows"/>.
/// <para>
/// week2 differs from week1 in exactly these ways: jobs JOAW330SYN0001 and 0002 leave S009 and appear in S018 DELIVERED;
/// job 0012 leaves S015 (IR) and appears in S017 (RWR); jobs 0026-0028 enter S009; the S004 card amount of 27 Sep 2026
/// is restated (2100 to 2150); S004 gains three rows dated 5 Oct 2026 (cash 400, card 450, upi 125 = 975, deliberately
/// different from the raw-CSV 5 Oct restatement of 250 cash + 275 card = 525); S003 gains one row dated 3 Oct 2026.
/// </para>
/// </summary>
internal static partial class ServiceFixtures
{
    public static readonly DateOnly Week1SnapshotDate = new(2026, 9, 28);
    public static readonly DateOnly Week2SnapshotDate = new(2026, 10, 5);

    public const string Week1FolderName = "Service Centre till 28 sep 2026";
    public const string Week2FolderName = "Service Centre till 05 oct 2026";

    public static string Root => Path.Combine(AppContext.BaseDirectory, "fixtures", "service-interim");

    /// <summary>S001-S040 (S038 header only; no S041) and the 00_ control workbook, dated 28 Sep 2026 by the folder name.</summary>
    public static string Week1Folder => Path.Combine(Root, "week1", Week1FolderName);

    /// <summary>The same families a week later (05 Oct 2026).</summary>
    public static string Week2Folder => Path.Combine(Root, "week2", Week2FolderName);

    /// <summary>week1 S009 and S002 in a folder whose name has no date (review H1: SERVICE_SNAPSHOT_DATE_NEEDED).</summary>
    public static string UndatedFolder => Path.Combine(Root, "undated", "Service Centre");

    /// <summary>week1 S009 with one row changed, dated 28 Sep 2026 again (IMPORT_PERIOD_ALREADY_PRESENT).</summary>
    public static string SameDateChangedFolder => Path.Combine(Root, "samedate-changed", Week1FolderName);

    public const string ControlFileName = "00_Service_Centre_Consolidation_Control.xlsx";

    /// <summary>
    /// GPRC history (lane L10, decision 16): S023 rows of 1, 3 and 5 Aug 2026 (claim documents GPAW330SYN0001-0003),
    /// dated 05 Aug 2026 by the folder name.
    /// </summary>
    public static string GprcHistoryFolder => Path.Combine(Root, "gprc", "Service Centre till 05 aug 2026");

    /// <summary>
    /// Raw GPRC CLAIM (S041) in ETP's export layout (sheet <see cref="GprcClaimSheet"/>, header row 1, Transaction Date
    /// with a time of day): documents GPAW330SYN0002-0005 dated 3-7 Aug 2026, folder date 07 Aug 2026. Documents 0002 and
    /// 0003 are also in <see cref="GprcHistoryFolder"/>; the union read takes them from S041 only.
    /// </summary>
    public static string GprcClaimFolder => Path.Combine(Root, "gprc", "Service Centre till 07 aug 2026");

    public const string GprcClaimFileName = "GPRC CLAIM 01.08.2026 TO 07.08.2026.xlsx";
    public const string GprcClaimSheet = "GPRC Claims Report";

    /// <summary>Lines in the S023 history file and in the S041 claim file.</summary>
    public const int GprcHistoryLines = 4, GprcClaimLines = 6;

    /// <summary>The union read of both files: 5 claim documents, 8 lines (2 from S023, 6 from S041), not 10.</summary>
    public const int GprcUnionDocuments = 5, GprcUnionLines = 8, GprcUnionLinesFromHistory = 2;

    /// <summary>
    /// The 35 families a week folder imports: ServiceInterimFamilies.Importable without S041 GPRC CLAIM, which is a raw
    /// export only (no consolidated workbook) and has its own fixtures (<see cref="GprcClaimFolder"/>).
    /// </summary>
    public static IReadOnlyList<string> ExpectedImported { get; } =
    [
        "S002", "S003", "S004", "S006", "S007", "S008", "S009", "S010", "S011", "S012", "S013", "S014", "S015", "S016",
        "S017", "S018", "S019", "S020", "S021", "S022", "S023", "S024", "S025", "S026", "S029", "S030", "S031", "S032",
        "S033", "S034", "S035", "S036", "S037", "S039", "S040",
    ];

    /// <summary>The files a week folder reports Not needed, with their diagnostic code (null for the 00_ control file).</summary>
    public static IReadOnlyList<(string File, string? Code)> ExpectedNotNeeded { get; } =
    [
        ("S001_RepairRegister.xlsx", "FAMILY_DERIVED"),
        ("S005_Tender_Collection_SUMMARY.xlsx", "SERVICE_FAMILY_NOT_NEEDED"),
        ("S027_TATReport.xlsx", "SERVICE_FAMILY_DEFERRED"),
        ("S028_TechnicianProductivityReport.xlsx", "SERVICE_FAMILY_DEFERRED"),
        ("S038_SRNReport.xlsx", "SERVICE_FAMILY_NOT_NEEDED"),
        (ControlFileName, null),
    ];

    /// <summary>The fixture file of a family in a folder, e.g. <c>S009_PendingRepair.xlsx</c>.</summary>
    public static string FileOf(string folder, string reportCode) =>
        Directory.GetFiles(folder, reportCode + "_*.xlsx").Single();
}
