-- Service interim lane L10 (decision 16, 4 Oct 2026): two read views for section C_SERVICE_READ of migration 0048.
--
-- WHERE THIS GOES. Section C is lane L4's and is generated by scripts/service-centre/generate_read_sql.py (branch
-- fixsvc/l4-views). This file is NOT run on its own and is not a migration. The integrator (or L4) makes the generator
-- emit the text between the two "L10 block" marker lines below verbatim, after dbo.v_service_money_changes and before
-- the GRANT block, and adds both view names to the generator's `views` list (GRANT SELECT / DENY writes). It also needs
-- S041 in the generator's IMPORTABLE list and DATELOG = transaction_date (see E:\ETP\Migration 2026-10-04\lanes\svc-l10.md,
-- patch plan L4-1). ServiceGprcAndMoneyViewTextTests pins this file; ServiceGprcClaimsSqlTests runs it after section C.
--
-- >>> L10 block begin
-- 8. GPRC claim lines from both GPRC families (decision 16, Q6/Q8). S023 GPRC_Report is the consolidated history (up to
-- 5 Aug 2026); S041 GPRC CLAIM is the raw export (from 1 Aug 2026). Each family's rows are first chosen by its own
-- DateLog rule (v_service_datelog_readings, reading_rank 1: S023 by TransDate, S041 by the date part of Transaction Date).
-- Then the union rule: S041 wins per claim document. An S023 line is read only when no winning S041 line has the same
-- document number; an S023 line without a document number is read only on a date that has no winning S041 line. So a
-- claim in both families (the 1-5 Aug overlap) is counted once, from S041, and a claim only S023 holds is kept.
-- No customer column: the counterparty is not needed by any screen.
EXEC(N'CREATE OR ALTER VIEW dbo.v_service_gprc_claims AS
WITH claims AS (
  SELECT r.import_file_id,w.snapshot_date,r.transaction_date business_date,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),r.document_number))),N'''') document_number,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),r.job_order_number))),N'''') job_order_number,
    CONVERT(nvarchar(100),r.item_id) item_id,r.quantity,CONVERT(nvarchar(100),r.account_number) account_number,
    r.price,r.net_amount,r.tax_amount,r.gross_amount,r.taxable,r.total_tax,r.igst_value,r.net_amount_inc_tax,r.value,r.ucp_value
  FROM dbo.etp_landing_s041 r JOIN dbo.v_service_datelog_readings w ON w.report_code=''S041'' AND w.reading_rank=1
    AND w.import_file_id=r.import_file_id AND w.business_date=r.transaction_date
), history AS (
  SELECT r.import_file_id,w.snapshot_date,r.transdate business_date,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),r.documentnum))),N'''') document_number,
    NULLIF(LTRIM(RTRIM(CONVERT(nvarchar(100),r.jonumber))),N'''') job_order_number,
    CONVERT(nvarchar(100),r.itemid) item_id,r.quantity,CONVERT(nvarchar(100),r.accountnum) account_number,
    r.price,r.netamount net_amount,r.taxamount tax_amount,r.grossamount gross_amount,r.taxable,r.totaltax total_tax,
    r.igstvalue igst_value,r.netamountinctax net_amount_inc_tax,r.value,r.ucpvalue ucp_value
  FROM dbo.etp_landing_s023 r JOIN dbo.v_service_datelog_readings w ON w.report_code=''S023'' AND w.reading_rank=1
    AND w.import_file_id=r.import_file_id AND w.business_date=r.transdate
)
SELECT ''S041'' report_code,business_date,document_number,job_order_number,item_id,quantity,account_number,price,net_amount,
  tax_amount,gross_amount,taxable,total_tax,igst_value,net_amount_inc_tax,value,ucp_value,snapshot_date,import_file_id
FROM claims
UNION ALL
SELECT ''S023'',h.business_date,h.document_number,h.job_order_number,h.item_id,h.quantity,h.account_number,h.price,h.net_amount,
  h.tax_amount,h.gross_amount,h.taxable,h.total_tax,h.igst_value,h.net_amount_inc_tax,h.value,h.ucp_value,h.snapshot_date,h.import_file_id
FROM history h
WHERE NOT EXISTS(SELECT 1 FROM claims c WHERE c.document_number=h.document_number)
  AND (h.document_number IS NOT NULL OR NOT EXISTS(SELECT 1 FROM claims c WHERE c.business_date=h.business_date))');

-- 9. Manual Service entries for the money check (decision 16, Q1-Q4). One row per shop, date and SERVICE_* field.
-- tender is CASH, CARD or UPI for the three compared fields and NULL for SERVICE_WDC, which stays out of the comparison.
-- is_service_money_shop marks the one shop that enters all of the Service centre's money (Q1, the Titan World shop);
-- an entry at any other shop is listed separately by the money screen and never added in (ServiceMoneyCheck).
-- The store code is written here, in SQL, because runtime C# holds no store-code literal.
EXEC(N'CREATE OR ALTER VIEW dbo.v_service_manual_money AS
SELECT m.business_date,m.store_code,s.store_name,m.field_code,m.numeric_value amount,
  CASE m.field_code WHEN ''SERVICE_CASH'' THEN ''CASH'' WHEN ''SERVICE_CARD'' THEN ''CARD'' WHEN ''SERVICE_UPI'' THEN ''UPI'' END tender,
  CONVERT(bit,CASE WHEN m.store_code=''WLMHW'' THEN 1 ELSE 0 END) is_service_money_shop
FROM dbo.manual_operational_inputs m LEFT JOIN dbo.stores s ON s.store_code=m.store_code
WHERE m.field_code LIKE ''SERVICE[_]%'' AND m.numeric_value IS NOT NULL');
-- <<< L10 block end
