"""Generate section B_SERVICE_LANDING of migration 0048 from the import catalogue.

Service interim (S-2), decision 15, 3 Oct 2026. Lane L2.

For each of the 36 importable Service families (ServiceInterimFamilies.Importable) this writes, in the
1.9.3 shape of a landing family:
  - table dbo.etp_landing_snnn (0018 shape: etp_row_id, import_file_id, source_lineage_id, content_key,
    then one column per catalogue Columns entry, in catalogue order);
  - index IX_etp_landing_snnn_file;
  - the locked-day trigger, text identical to 0018's (CREATE OR ALTER through EXEC);
  - dbo.append_etp_landing_snnn with the 0025 guards (positional @v0..@vN in catalogue Columns order,
    which is what PhaseOneImportPersistence passes);
  - DENY INSERT,UPDATE,DELETE to etp_store_manager,etp_viewer and GRANT EXECUTE to etp_store_manager,etp_owner.

Only the text between the B_SERVICE_LANDING markers of 0048 is replaced; nothing else in the file changes.
The output is deterministic: re-running over an unchanged catalogue rewrites the same bytes.
ServiceLandingMigrationTests renders the same text in C# and compares it with the committed section.

  python scripts/service-centre/generate_landing_sql.py            # rewrite section B in place
  python scripts/service-centre/generate_landing_sql.py --check    # exit 1 if section B is not current
  python scripts/service-centre/generate_landing_sql.py --catalogue <json> --migration <sql>   # other inputs

The script never reads real workbooks and never connects to a database.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOGUE = ROOT / "src" / "Etp.Reporting.Import" / "Profiles" / "EtpReportFamilies.json"
MIGRATION = ROOT / "database" / "migrations" / "0048_service_centre_interim.sql"
SECTION = "B_SERVICE_LANDING"
BEGIN_MARKER = f"-- >>> {SECTION} begin"
END_MARKER = f"-- <<< {SECTION} end"

# Mirror of ServiceInterimFamilies.Importable (src/Etp.Reporting.Import/Service/ServiceInterimFamilies.cs).
# ServiceLandingMigrationTests checks that the committed section holds a table for exactly that set.
# S041 GPRC CLAIM joined on 4 Oct 2026 (decision 16, Q6: a new family with its own table, still inside 0048; lane L10).
IMPORTABLE = (["S002", "S003", "S004"] + [f"S{n:03d}" for n in range(6, 27)]
              + [f"S{n:03d}" for n in range(29, 38)] + ["S039", "S040", "S041"])
assert len(IMPORTABLE) == 36 and len(set(IMPORTABLE)) == 36

SQL_TYPES = {"Text": "nvarchar(max)", "Identifier": "nvarchar(max)", "Decimal": "decimal(19,4)", "Date": "date", "Integer": "int"}

# 0018's locked-day trigger, with CREATE OR ALTER so a re-run is harmless; only the table name varies.
TRIGGER = ("EXEC(N'CREATE OR ALTER TRIGGER dbo.trg_{table}_locked ON dbo.[{table}] AFTER INSERT,UPDATE,DELETE AS BEGIN SET NOCOUNT ON; "
           "IF EXISTS(SELECT 1 FROM (SELECT import_file_id FROM inserted UNION SELECT import_file_id FROM deleted) x "
           "JOIN dbo.import_files f ON f.import_file_id=x.import_file_id JOIN dbo.daily_reporting_days d ON d.store_code=f.store_code "
           "AND d.business_date BETWEEN f.period_start AND f.period_end WHERE d.status=''LOCKED'') "
           "THROW 51243,''A day inside this export is finalised. Reopen it before changing its data.'',1; END');")

# 0025's append-procedure guards; only the report code varies.
PROCEDURE_GUARDS = """AS BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON;
 IF COALESCE(IS_ROLEMEMBER(''etp_store_manager''),0)<>1 AND COALESCE(IS_ROLEMEMBER(''etp_owner''),0)<>1
    AND COALESCE(IS_SRVROLEMEMBER(''sysadmin''),0)<>1
  THROW 51420,''Owner or Store Manager permission is required.'',1;
 IF @@TRANCOUNT=0 THROW 51422,''Import writes require an enclosing transaction.'',1;
 IF NOT EXISTS(SELECT 1 FROM dbo.import_files f WITH(UPDLOCK,HOLDLOCK)
   JOIN dbo.import_batches b ON b.import_batch_id=f.import_batch_id
   WHERE f.import_file_id=@file AND f.is_superseded=0 AND f.data_truth_version=1 AND b.status=''Processing'')
  THROW 51422,''The source import is not open for writing.'',1;
 IF NOT EXISTS(SELECT 1 FROM dbo.source_lineage l JOIN dbo.import_files f ON f.import_file_id=l.import_file_id
   WHERE l.source_lineage_id=@lineage AND l.import_file_id=@file AND f.report_code=''{code}'')
  THROW 51422,''The source row does not belong to this report import.'',1;"""

HEADER = """-- Generated by scripts/service-centre/generate_landing_sql.py from src/Etp.Reporting.Import/Profiles/EtpReportFamilies.json.
-- Regenerate rather than edit; ServiceLandingMigrationTests fails when this section and the catalogue disagree.
-- The {count} importable Service families (ServiceInterimFamilies.Importable), each in the 1.9.3 landing shape:
-- table (0018), file index, locked-day trigger (0018 text), append procedure (0025 guards), DENY and GRANT.
-- No table for S001 (derived), S005 and S038 (not needed) or S027 and S028 (deferred to P8).
-- dbo.promote_import_superset needs no Service block: its content-key superset check over dbo.etp_import_content
-- covers untyped families, and the per-report blocks are only for typed Retail tables. 0025 is not edited.
-- No stores row (section A owns AW330), no import_profiles seed and no transaction (the runner supplies it).
"""


def load_families(catalogue_path):
    families = json.loads(Path(catalogue_path).read_text(encoding="utf-8"))
    chosen = [f for f in families
              if re.fullmatch(r"S\d{3}", f["FamilyCode"]) and not f.get("Derived", False) and f["FamilyCode"] in IMPORTABLE]
    chosen.sort(key=lambda f: f["FamilyCode"])
    codes = [f["FamilyCode"] for f in chosen]
    missing = sorted(set(IMPORTABLE) - set(codes))
    if missing:
        sys.exit(f"The catalogue has no importable entry for: {', '.join(missing)}")
    for family in chosen:
        code = family["FamilyCode"]
        assert family["ReportCode"] == code, code
        assert family["TableName"] == f"etp_landing_{code.lower()}", code
        assert family["IsTyped"] is False, code
        names = [c["CanonicalField"] for c in family["Columns"]]
        assert names and len(set(names)) == len(names), code
        assert all(re.fullmatch(r"[a-z0-9_]+", n) for n in names), code
        assert all(c["DataType"] in SQL_TYPES for c in family["Columns"]), code
    return chosen


def render_family(family):
    code, table, columns = family["FamilyCode"], family["TableName"], family["Columns"]
    names = [c["CanonicalField"] for c in columns]
    types = [SQL_TYPES[c["DataType"]] for c in columns]
    parameters = [f"@v{i}" for i in range(len(columns))]
    last = len(columns) - 1
    lines = [f"-- {code} {family['Name']} ({len(columns)} columns)",
             f"IF OBJECT_ID(N'dbo.{table}', N'U') IS NULL",
             f"CREATE TABLE dbo.[{table}] (",
             " etp_row_id bigint IDENTITY PRIMARY KEY,",
             " import_file_id bigint NOT NULL REFERENCES dbo.import_files(import_file_id),",
             " source_lineage_id bigint NOT NULL UNIQUE REFERENCES dbo.source_lineage(source_lineage_id),",
             " content_key varchar(80) NOT NULL,"]
    lines += [f" [{n}] {t} NULL" + ("," if i < last else "") for i, (n, t) in enumerate(zip(names, types))]
    lines += [");",
              "",
              f"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{table}_file' AND object_id = OBJECT_ID(N'dbo.{table}'))",
              f" CREATE INDEX IX_{table}_file ON dbo.[{table}](import_file_id);",
              "",
              TRIGGER.format(table=table),
              "",
              f"EXEC(N'CREATE OR ALTER PROCEDURE dbo.append_{table}",
              " @file bigint,@lineage bigint,@key varchar(80),"]
    lines += [f" {p} {t}" + ("," if i < last else "") for i, (p, t) in enumerate(zip(parameters, types))]
    lines.append(PROCEDURE_GUARDS.format(code=code))
    lines.append(f" INSERT dbo.[{table}](import_file_id,source_lineage_id,content_key,{','.join(f'[{n}]' for n in names)})")
    lines.append(f" VALUES(@file,@lineage,@key,{','.join(parameters)});")
    lines += [" INSERT dbo.etp_import_content(import_file_id,source_row_number,content_key)",
              " SELECT @file,source_row_number,@key FROM dbo.source_lineage WHERE source_lineage_id=@lineage;",
              "END');",
              "",
              f"DENY INSERT,UPDATE,DELETE ON dbo.[{table}] TO etp_store_manager,etp_viewer;",
              f"GRANT EXECUTE ON dbo.append_{table} TO etp_store_manager,etp_owner;"]
    return "\n".join(lines) + "\n"


def render_section(families):
    """The text strictly between the marker lines, with LF line ends."""
    return HEADER.format(count=len(families)) + "".join("\n" + render_family(f) for f in families)


def splice(text, section):
    newline = "\r\n" if "\r\n" in text else "\n"
    normal = text.replace("\r\n", "\n")
    begin = normal.find(BEGIN_MARKER + "\n")
    end = normal.find("\n" + END_MARKER)
    if begin < 0 or end < 0 or normal.count(BEGIN_MARKER) != 1 or normal.count(END_MARKER) != 1:
        sys.exit(f"The migration must hold exactly one '{BEGIN_MARKER}' line and one '{END_MARKER}' line.")
    start = begin + len(BEGIN_MARKER) + 1
    if end + 1 < start:
        sys.exit("The section markers are out of order.")
    updated = normal[:start] + section + normal[end + 1:]
    return updated.replace("\n", newline)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--catalogue", default=str(CATALOGUE))
    parser.add_argument("--migration", default=str(MIGRATION))
    parser.add_argument("--check", action="store_true", help="exit 1 if the section is not what the catalogue gives")
    args = parser.parse_args()

    families = load_families(args.catalogue)
    migration = Path(args.migration)
    raw = migration.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw[3:].decode("utf-8") if bom else raw.decode("utf-8")
    updated = splice(text, render_section(families))
    if args.check:
        if updated != text:
            print(f"{migration.name}: section {SECTION} is not current; run generate_landing_sql.py", file=sys.stderr)
            return 1
        print(f"{migration.name}: section {SECTION} is current ({len(families)} families)")
        return 0
    if updated != text:
        migration.write_bytes((b"\xef\xbb\xbf" if bom else b"") + updated.encode("utf-8"))
    print(f"{migration.name}: section {SECTION} written for {len(families)} families")
    return 0


if __name__ == "__main__":
    sys.exit(main())
